Delete rudiment widgets
mendix/WorkflowCommons pull request #11
Opened 2022-05-16 07:22 UTC by dimas9009

1. Added step to delete rudiment widgets.
2. Added file to describe allowed widgts in final mpk

2022-05-16 13:03 UTC, allard-mx requested changes
Seems to work really well. Added one review comment.

2022-05-16 13:03 UTC, allard-mx commented on .github/workflows/build.yml
> +                echo "Deleting widget: $i" | tee $GITHUB_WORKSPACE/out/deletedWidgets.log
Currently the deletedWidgets.log file seems to be overwritten for every widget that gets deleted. In the results, the file currently only contains 'Deleting widget: com.mendix.widget.web.DatagridTextFilter.mpk', which is the latest widget that got deleted.

2022-05-16 13:14 UTC, allard-mx requested changes
We found one other issue: the package.xml is currently not updated. This results in Studio Pro giving a warning that the removed widget files will still be imported, even though this is not the case.

2022-05-18 09:45 UTC, allard-mx approved these changes

2022-05-18 10:48 UTC, MendixMurshed approved these changes
great, working nicely

2022-05-18 11:15 UTC, merged